server:
  port: 8090

# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mybatisplusdemo?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  main:
    banner-mode: off # 关闭SpringBoot启动图标(banner)
  # swagger配置
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    # thymeleaf页面模板配置
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
    view:
      prefix: classpath:/templates/
      suffix: .html
  resources:
    static-locations: classpath:/templates/,classpath:/static/
#  elasticsearch:
#    rest:
#      uris: 192.168.1.195:9200,192.168.1.195:9201,192.168.1.195:9202 #设置集群
  messages:
    basename: i18n/messages,i18n/messages_en,i18n/messages_zh_CN
    encoding: UTF-8

  #CacheManager
  cache:
    type: simple

  # JavaMailSender
  mail:
    host: smtp.qq.com
    username: 1724059570@qq.com
    password: arrvvtxmkzdlcjgf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  shardingsphere:
    datasource:
      names: ds0  # ✅ 这里一定要指定一个或多个数据源名称

      ds0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://localhost:3306/mybatisplusdemo?serverTimezone=UTC&useSSL=false
        username: root
        password: 123456

    rules:
      sharding:
        tables:
          order:
            actual-data-nodes: ds0.order_$->{202501..202507}
            table-strategy:
              standard:
                sharding-column: order_date
                sharding-algorithm-name: order-date-algorithm

          pet_chat_message:
            actual-data-nodes: ds0.pet_chat_message_$->{202501..202507}
            table-strategy:
              standard:
                sharding-column: creation_date
                sharding-algorithm-name: pet-chat-message-algorithm

          pet_chat_sender:
            actual-data-nodes: ds0.pet_chat_sender_$->{202501..202507}
            table-strategy:
              standard:
                sharding-column: creation_date
                sharding-algorithm-name: pet-chat-sender-algorithm

          pet_chat_accepter:
            actual-data-nodes: ds0.pet_chat_accepter_$->{202501..202507}
            table-strategy:
              standard:
                sharding-column: creation_date
                sharding-algorithm-name: pet-chat-accepter-algorithm

        sharding-algorithms:
          order-date-algorithm:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: com.example.mybatplusdemo.sharedingjdbc.OrderDateShardingAlgorithm
          # pet_chat_message 表的分片算法
          pet-chat-message-algorithm:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: com.example.mybatplusdemo.sharedingjdbc.PetChatMessageShardingAlgorithm
          pet-chat-sender-algorithm:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: com.example.mybatplusdemo.sharedingjdbc.PetChatSenderShardingAlgorithm
          pet-chat-accepter-algorithm:
            type: CLASS_BASED
            props:
              strategy: standard
              algorithmClassName: com.example.mybatplusdemo.sharedingjdbc.PetChatAccepterShardingAlgorithm
    props:
      sql-show: true  # 可选：打印 SQL 日志


# mybatis-plus日志控制台输出
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: off
#  mapperLocations: classpath:com/example/mybatplusdemo/mapper/*.xml
#  mapper-locations: classpath:com/example/mybatplusdemo/mapper/*Mapper.xml
  mapper-locations: classpath:mapper/*.xml

#xxl:
#  job:
#    admin:
#      addresses: http://127.0.0.1:8080/xxl-job-admin
#    accessToken: default_token
#    executor:
#      appname: xxl-job-executor-sample
#      address:
#      ip:
#      port: 9999
#      logpath: /data/applogs/xxl-job/jobhandler
#      logretentiondays: 30
#### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
#xxl.job.admin.addresses=http://127.0.0.1:8080/xxl-job-admin
#
#### xxl-job, access token
#xxl.job.accessToken=default_token
#
#### xxl-job executor appname
#xxl.job.executor.appname=xxl-job-executor-sample
#### xxl-job executor registry-address: default use address to registry , otherwise use ip:port if address is null
#xxl.job.executor.address=
#### xxl-job executor server-info
#xxl.job.executor.ip=
#xxl.job.executor.port=9999
#### xxl-job executor log-path
#xxl.job.executor.logpath=/data/applogs/xxl-job/jobhandler
#### xxl-job executor log-retention-days
#xxl.job.executor.logretentiondays=30


#pageOffice
file:
  save:
    path: d:/page/


minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: chen
  secure: false


google:
  client-id: 788764694057-uad5gib84d802j5g87kvtud8dh84p7u6.apps.googleusercontent.com
  client-secret: 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
  redirect-uri: http://localhost:8090/oauth/callback


hitpay:
  merchant-id: YOUR_MERCHANT_ID
  api-key: a5218db6c252258c9b3f4989b52d898b05a070b01ad812abbcfcdf0ee354014c
#  api-base-url: https://api.hitpayapp.com/v1/
  api-base-url: https://api.sandbox.hit-pay.com/v1/
  endpoint: https://api.sandbox.hit-pay.com/v1
  webhook-secret: your_webhook_secret_here


