server:
  port: 8090

# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/mybatisplusdemo?characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  main:
    banner-mode: off # 关闭SpringBoot启动图标(banner)
  # swagger配置
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    # thymeleaf页面模板配置
    thymeleaf:
      prefix: classpath:/templates/
      suffix: .html
    view:
      prefix: classpath:/templates/
      suffix: .html
  resources:
    static-locations: classpath:/templates/,classpath:/static/
#  elasticsearch:
#    rest:
#      uris: 192.168.1.195:9200,192.168.1.195:9201,192.168.1.195:9202 #设置集群
  messages:
    basename: i18n/messages,i18n/messages_en,i18n/messages_zh_CN
    encoding: UTF-8

  #CacheManager
  cache:
    type: simple

  # JavaMailSender
  mail:
    host: smtp.qq.com
    username: 1724059570@qq.com
    password: arrvvtxmkzdlcjgf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

# mybatis-plus日志控制台输出
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: off
#  mapperLocations: classpath:com/example/mybatplusdemo/mapper/*.xml
#  mapper-locations: classpath:com/example/mybatplusdemo/mapper/*Mapper.xml
  mapper-locations: classpath:mapper/*.xml

#xxl:
#  job:
#    admin:
#      addresses: http://127.0.0.1:8080/xxl-job-admin
#    accessToken: default_token
#    executor:
#      appname: xxl-job-executor-sample
#      address:
#      ip:
#      port: 9999
#      logpath: /data/applogs/xxl-job/jobhandler
#      logretentiondays: 30
#### xxl-job admin address list, such as "http://address" or "http://address01,http://address02"
#xxl.job.admin.addresses=http://127.0.0.1:8080/xxl-job-admin
#
#### xxl-job, access token
#xxl.job.accessToken=default_token
#
#### xxl-job executor appname
#xxl.job.executor.appname=xxl-job-executor-sample
#### xxl-job executor registry-address: default use address to registry , otherwise use ip:port if address is null
#xxl.job.executor.address=
#### xxl-job executor server-info
#xxl.job.executor.ip=
#xxl.job.executor.port=9999
#### xxl-job executor log-path
#xxl.job.executor.logpath=/data/applogs/xxl-job/jobhandler
#### xxl-job executor log-retention-days
#xxl.job.executor.logretentiondays=30


#pageOffice
file:
  save:
    path: d:/page/


minio:
  endpoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
  bucketName: chen
  secure: false


google:
  client-id: 788764694057-uad5gib84d802j5g87kvtud8dh84p7u6.apps.googleusercontent.com
  client-secret: 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
  redirect-uri: http://localhost:8090/oauth/callback